### ISSUE TITLE
My transcription up to 2:17:00

### ISSUE THREAD

**Issue by lifthrasiir** [theinternetftw/xkcd2601#4]
![image](https://user-images.githubusercontent.com/323836/161366520-5d4eb1b5-9b1a-4b1c-90f6-66ae7a4612a6.png)

See my [gist](https://gist.github.com/lifthrasiir/461fa05ea6785d7252abd1bcdb9bb288) for the transcript and an interactive runner I've used. My attempt is very quick one and I used a lot of heuristics not to verify everything, so this should be considered preliminary and I'm okay with it being discarded in favor of better transcripts. In particular the initial 11 minutes came from explainxkcd comments which seem to have some missing bits and I guess you should ignore them.

**Comment by theinternetftw** [comment]
I really dig the idea of an itty bitty canvas interpreter. Will double check the transcript against sound (at 2x speed) and pull it in.

**Comment by lifthrasiir** [comment]
Since my transcript is going to make its way into this repo (thank you for the additional verification!), some comments on the code and also the machine-generated transcript I based on:

* Most numbers are indeed correct, but some numbers are missing. Signs are less correct and needs manual check.
* The code is (thought to be) regular except for the initial part and consecutive `CUBIC` commands tend to have similar arguments, so it is not hard to see *which* number is missing.
* In addition to spelt numbers, the machine-generated transcript commonly transcribes `120 to`, `120-` or `120:` for `122`. I've mostly fixed this from my gist automatically, but some ambiguities remain (for example `-` in `120-` might be a sign for the next number as well).
* It is often the case that numbers like `120 3` are transcribed as `123`. This is obvious for humans but hard to automatically fix.
* The first argument to `CUBIC` can be seen frequently missing in comparison to other arguments.
* `PENUP` seems pretty prone to be mangled.
* Redundant things like `FORWARD 0` or `CUBIC ... -0 ...` do appear. I believe the original image was prepared as a SVG path and naively translated to LOGO for this reason.

**Comment by theinternetftw** [comment]
Thanks! I've added up to 2:17:00 (and went onwards to the 2:20:00 boundary), but reading and correcting a finicky machine transcript might be slower than just listening and typing (especially if playing back the file at increased speed), so may or may not continue to refer to it myself. Some folks helping out might find doing so faster, though, so that write up is a useful resource regardless of what I end up doing personally.

I might end up writing something like your canvas code that's enough of a real parser that it can handle the various variations in what needs to be parsed that's showing up in these commits. It'd be great if folks didn't have to find a compatible logo interpreter for their OS to contribute or view the thing.
